language: cpp
    
branches:
  only:
    - master
    - develop

matrix:
   include:
     - os: osx
       osx_image: xcode12.2
       compiler: clang
       env:
         - MATRIX_EVAL="CC=clang && CXX=clang++"
         
before_install:
  - |
    if [ $TRAVIS_EVENT_TYPE = 'pull_request' ]
    then
        export BRANCH="pr_${TRAVIS_PULL_REQUEST}_${TRAVIS_PULL_REQUEST_BRANCH}"
        git fetch origin pull/$TRAVIS_PULL_REQUEST/head:$BRANCH
    else
        export BRANCH=$TRAVIS_BRANCH
    fi
  - echo ${BRANCH}
  - git checkout $BRANCH
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install: #travis_wait 30 ./scripts/updatecmake.sh  #- while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - brew update
  - brew outdated cmake || brew upgrade cmake

script: 
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest -VV --output-on-failure -C Debug

notifications:
  email:
    recipients:
      - rokodev@mail.ru
    on_success: change
    on_failure: always
    