# if: (type = push AND branch IN (master, dev)) OR (type = pull_request)

language: cpp
    
# branches:
#   only:
#     - master
#     - develop
#     - CLIENT-10

matrix:
   include:
     - os: linux
       name: Linux Clang 10
       dist: focal
       compiler: clang
       addons:
         apt:
           packages:
             - clang-10
       env: 
         - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
     - os: osx
       osx_image: xcode12.2
       compiler: clang
       env:
         - MATRIX_EVAL="CC=clang && CXX=clang++"
         
before_install:
  - |
    if [ $TRAVIS_EVENT_TYPE = 'pull_request' ]
    then
        export BRANCH="pr_${TRAVIS_PULL_REQUEST}_${TRAVIS_PULL_REQUEST_BRANCH}"
        git fetch origin pull/$TRAVIS_PULL_REQUEST/head:$BRANCH
    else
        export BRANCH=$TRAVIS_BRANCH
    fi
  - echo $BRANCH
  - git checkout $BRANCH
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install: #travis_wait 30 ./scripts/updatecmake.sh
  - cmake -version
  - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - ./scripts/updatecmake.sh

script: 
  - echo "going to start build"
  - echo $PATH
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest -VV --output-on-failure -C Debug

notifications:
  email:
    recipients:
      - rokodev@mail.ru
    on_success: change
    on_failure: always
    