# if: (type = push AND branch IN (master, dev)) OR (type = pull_request)

language: cpp
    
# branches:
#   only:
#     - master
#     - develop
#     - CLIENT-10

matrix:
   include:
     - os: linux
       name: Linux Clang 10
       dist: focal
       compiler: clang
       addons:
         apt:
           packages:
             - clang-10
       env: 
         - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
     - os: osx
       osx_image: xcode12.2
       compiler: clang
       env:
         - MATRIX_EVAL="CC=clang && CXX=clang++"
         
before_install:
  - |
    if [ $TRAVIS_EVENT_TYPE = 'pull_request' ]; then
        export BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
    else
        export BRANCH=$TRAVIS_BRANCH
    fi
  - echo ${TRAVIS_PULL_REQUEST_BRANCH}
  - git checkout $TRAVIS_PULL_REQUEST_BRANCH
  - git submodule update --init --recursive
  - eval "${MATRIX_EVAL}"

install: #travis_wait 30 ./scripts/updatecmake.sh
  - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - ./scripts/updatecmake.sh

script: 
  # - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" -D CMAKE_CXX_COMPILER=${COMPILER}"
  # Check versions of gcc, g++ and cmake
  #
  # Warning: A newer Command Line Tools release is available.
  # Update them from Software Update in the App Store or run:
  # softwareupdate --all --install --force
  
  # If that doesn't show you an update run:
  #   sudo rm -rf /Library/Developer/CommandLineTools
  #   sudo xcode-select --install
  - echo "going to start build"
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest -VV --output-on-failure -C Debug

notifications:
  email:
    recipients:
      - rokodev@mail.ru
    on_success: change
    on_failure: always
    